import { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { Plus, Trash2 } from 'lucide-react';
import { 
  useReports, 
  useCreateReport, 
  useDeleteReport 
} from '../hooks/useReports';
import ReportFormPopup from '../../components/ReportFormPopup.js';
import { getCurrentUser } from '../services/auth.api';

function Reports({ searchValue }) {
  const location = useLocation();
  const [showPopup, setShowPopup] = useState(false);
  const [formData, setFormData] = useState({ 
    report_name: '', 
    report_type: '',
  });

  const [activeTab, setActiveTab] = useState('reports');

  useEffect(() => {
    const path = location.pathname;
    if (path.includes('/admin/reports')) {
      setActiveTab('reports');
    }
  }, [location.pathname]);

  const { data: reports = [], isLoading } = useReports();
  const createReportMutation = useCreateReport();
  const deleteReportMutation = useDeleteReport();

  const handleAddReport = async (e) => {
    e.preventDefault();
    try {
      // Get current user for generated_by field
      const currentUser = getCurrentUser();
      const apiData = {
        ...formData,
        generated_by: currentUser?.id || null
      };
      
      await createReportMutation.mutateAsync(apiData);
      setFormData({ report_name: '', report_type: '' });
      setShowPopup(false);
    } catch (error) {
      console.error("Failed to create report:", error);
      alert('Failed to create report. Please try again.');
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this report?')) {
      try {
        await deleteReportMutation.mutateAsync(id);
      } catch (error) {
        alert('Failed to delete report. Please try again.');
      }
    }
  };

  const filteredReports = searchValue
    ? reports.filter((report) =>
        report.report_name?.toLowerCase().includes(searchValue.toLowerCase())
      )
    : reports;

  return (
    <>
        <section className="flex-1 h-full bg-white mx-6 my-5 rounded-lg p-5 border-2 border-[#c7d5f2] flex flex-col">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-semibold max-[856px]:text-sm ">Report Management</h2>
            <button
              onClick={() => {
                setFormData({ report_name: '', report_type: '' });
                setShowPopup(true);
              }}
              className="max-[856px]:scale-90 bg-[#0b0b3b] text-white px-4 py-2 rounded hover:bg-[#1a1a6a] transition-colors text-sm font-medium flex items-center gap-2"
            >
              <Plus size={15}/> Generate Report
            </button>
          </div>

          <div className="overflow-x-auto flex-1 h-full">
            <table className="w-full border-collapse text-left text-sm min-w-max">
              <thead>
                <tr>
                  <th className="p-3 border-b border-gray-300 font-semibold">Report Name</th>
                  <th className="p-3 border-b border-gray-300 font-semibold">Report Type</th>
                  <th className="p-3 border-b border-gray-300 font-semibold">Generated At</th>
                  <th className="p-3 border-b border-gray-300 font-semibold">Generated By</th>
                  <th className="p-3 border-b border-gray-300 font-semibold">File Path</th>
                  <th className="p-3 border-b border-gray-300 font-semibold">Action</th>
                </tr>
              </thead>
              <tbody>
                {isLoading ? (
                  <tr>
                    <td colSpan="6" className="p-3 text-center text-gray-500">Loading...</td>
                  </tr>
                ) : filteredReports.length === 0 ? (
                  <tr>
                    <td colSpan="6" className="p-3 text-center text-gray-500">No reports found</td>
                  </tr>
                ) : (
                  filteredReports.map((report) => (
                    <tr key={report.id} className="border-b border-gray-200">
                      <td className="p-3">{report.report_name}</td>
                      <td className="p-3">{report.report_type}</td>
                      <td className="p-3">{report.generated_at}</td>
                      <td className="p-3">{report.generated_by}</td>
                      <td className="p-3"><a href={report.file_path} target="_blank" rel="noreferrer" className="text-blue-500 hover:underline">Download</a></td>
                      <td className="p-3">
                        <button 
                          onClick={() => handleDelete(report.id)}
                          className="mr-2 text-lg hover:scale-125 transition-transform" 
                          title="Delete"><Trash2 size={20}/></button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </section>
      <ReportFormPopup 
        showPopup={showPopup} 
        formData={formData} 
        setFormData={setFormData} 
        handleAddReport={handleAddReport} 
        setShowPopup={setShowPopup} 
      />
    </>
  );
}

export default Reports;