import { useState } from 'react';
import {
  useReports,
  useCreateReport,
  useDeleteReport
} from '../hooks/useReports.js';
import ReportFormPopup from '../components/ReportFormPopup.jsx';
import CommonLayout from '../Layouts/CommonLayout.jsx';
import { getCurrentUser } from '../services/auth.api.js';

function Reports({ searchValue }) {
  const [showPopup, setShowPopup] = useState(false);
  const [formData, setFormData] = useState({
    report_name: '',
    report_type: '',
    file_path: ''
  });

  const { data: reports = [], isLoading } = useReports();
  const createReportMutation = useCreateReport();
  const deleteReportMutation = useDeleteReport();

  const handleAddReport = async (e) => {
    e.preventDefault();
    try {
      const currentUser = getCurrentUser();
      const apiData = {
        report_name: formData.report_name,
        report_type: formData.report_type,
        generated_by: currentUser?.user_id || '',
        file_path: formData.file_path || ''
      };

      await createReportMutation.mutateAsync(apiData);
      setFormData({ report_name: '', report_type: '', file_path: '' });
      setShowPopup(false);
    } catch (error) {
      console.error("Failed to create report:", error);
      alert('Failed to create report. Please try again.');
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this report?')) {
      try {
        await deleteReportMutation.mutateAsync(id);
      } catch (error) {
        alert('Failed to delete report. Please try again.');
      }
    }
  };

  const buttonBehaviour = () => {
    setFormData({ report_name: '', report_type: '', file_path: '' });
    setShowPopup(true);
  };

  const filteredReports = searchValue
    ? reports.filter((report) =>
      report.report_name?.toLowerCase().includes(searchValue.toLowerCase()) ||
      report.report_type?.toLowerCase().includes(searchValue.toLowerCase())
    )
    : reports;

  const title = "Report Management";
  const buttonText = "Generate Report";
  const columns = [
    { header: 'Report ID', accessor: 'report_id' },
    { header: 'Report Name', accessor: 'report_name' },
    { header: 'Report Type', accessor: 'report_type' },
    { header: 'Generated At', accessor: 'generated_at' },
    { header: 'Generated By', accessor: 'generated_by' },
    { header: 'File Path', accessor: 'file_path' },
    { header: 'Action', accessor: 'action' },
  ];

  const formPopup = (
    <ReportFormPopup
      showPopup={showPopup}
      formData={formData}
      setFormData={setFormData}
      handleAddReport={handleAddReport}
      setShowPopup={setShowPopup}
    />
  );

  return (
    <CommonLayout
      searchValue={searchValue}
      buttonBehaviour={buttonBehaviour}
      isLoading={isLoading}
      data={filteredReports}
      handleEdit={() => { }}
      handleDelete={handleDelete}
      title={title}
      buttonText={buttonText}
      columns={columns}
      formPopup={formPopup}
    />
  );
}

export default Reports;