import { useState } from 'react';
import DashboardLayout from '../layouts/DashboardLayout';
import { 
  useReports, 
  useCreateReport, 
  useDeleteReport 
} from '../hooks/useReports';
import ReportFormPopup from '../components/ReportFormPopup.jsx';

function Reports({ searchValue }) {
  const [showPopup, setShowPopup] = useState(false);
  const [formData, setFormData] = useState({ 
    report_name: '', 
    report_type: '',
  });

  const { data: reports = [], isLoading } = useReports();
  const createReportMutation = useCreateReport();
  const deleteReportMutation = useDeleteReport();

  const handleAddReport = async (e) => {
    e.preventDefault();
    try {
      await createReportMutation.mutateAsync(formData);
      setFormData({ report_name: '', report_type: '' });
      setShowPopup(false);
    } catch (error) {
      console.error("Failed to create report:", error);
      alert('Failed to create report. Please try again.');
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this report?')) {
      try {
        await deleteReportMutation.mutateAsync(id);
      } catch (error) {
        alert('Failed to delete report. Please try again.');
      }
    }
  };

  const filteredReports = searchValue
    ? reports.filter((report) =>
        report.report_name?.toLowerCase().includes(searchValue.toLowerCase())
      )
    : reports;

  return (
    <>
      <DashboardLayout activeTab="reports">
        <section className="flex-1 bg-white mx-6 my-5 rounded-lg p-5 border-2 border-[#c7d5f2] overflow-auto">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-semibold">Report Management</h2>
            <button
              onClick={() => {
                setFormData({ report_name: '', report_type: '' });
                setShowPopup(true);
              }}
              className="bg-[#0b0b3b] text-white px-4 py-2 rounded hover:bg-[#1a1a6a] transition-colors text-sm font-medium"
            >
              ➕ Generate Report
            </button>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-left text-sm">
              <thead>
                <tr>
                  <th className="p-3 border-b border-gray-300 font-semibold">Report Name</th>
                  <th className="p-3 border-b border-gray-300 font-semibold">Report Type</th>
                  <th className="p-3 border-b border--gray-300 font-semibold">Generated At</th>
                  <th className="p-3 border-b border-gray-300 font-semibold">Generated By</th>
                  <th className="p-3 border-b border-gray-300 font-semibold">File Path</th>
                  <th className="p-3 border-b border-gray-300 font-semibold">Action</th>
                </tr>
              </thead>
              <tbody>
                {isLoading ? (
                  <tr>
                    <td colSpan="6" className="p-3 text-center text-gray-500">Loading...</td>
                  </tr>
                ) : filteredReports.length === 0 ? (
                  <tr>
                    <td colSpan="6" className="p-3 text-center text-gray-500">No reports found</td>
                  </tr>
                ) : (
                  filteredReports.map((report) => (
                    <tr key={report.id} className="border-b border-gray-200">
                      <td className="p-3">{report.report_name}</td>
                      <td className="p-3">{report.report_type}</td>
                      <td className="p-3">{report.generated_at}</td>
                      <td className="p-3">{report.generated_by}</td>
                      <td className="p-3"><a href={report.file_path} target="_blank" rel="noreferrer" className="text-blue-500 hover:underline">Download</a></td>
                      <td className="p-3">
                        <button 
                          onClick={() => handleDelete(report.id)}
                          className="mr-2 text-lg hover:scale-125 transition-transform" 
                          title="Delete">🗑️</button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </section>
      </DashboardLayout>
      <ReportFormPopup 
        showPopup={showPopup} 
        formData={formData} 
        setFormData={setFormData} 
        handleAddReport={handleAddReport} 
        setShowPopup={setShowPopup} 
      />
    </>
  );
}

export default Reports;