import React, { useState, useRef } from "react";
import { BookOpen, Copy, Image } from "lucide-react";
import FormLayout from "../Layouts/FormLayout.jsx";
import BookCopiesPopup from "./BookCopiesPopup.jsx";

function BookFormPopup({
  showPopup,
  editMode,
  formData,
  setFormData,
  handleAddBook,
  setShowPopup,
  setEditMode,
  categories,
}) {
  const [showCopiesPopup, setShowCopiesPopup] = useState(false);
  const [fileName, setFileName] = useState("");
  const fileInputRef = useRef(null);

  const onFormChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setFileName(file.name);
      const reader = new FileReader();
      reader.onloadend = () => {
        // Strip the "data:image/...;base64," prefix for the backend (bytea)
        const base64 = reader.result.split(",")[1];
        setFormData({ ...formData, image_url: base64 });
      };
      reader.readAsDataURL(file);
      // Reset input value to allow selecting the same file again if needed
      e.target.value = "";
    }
  };

  const handleSaveBookCopies = (copiesArray) => {
    const updatedData = { ...formData, BookCopies: copiesArray };
    setFormData(updatedData);
    // Directly submit the book with the new copies
    if (handleAddBook) {
      handleAddBook(null, updatedData);
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    // Validate required fields
    if (!formData.name || !formData.name.trim()) {
      alert("Please enter a book name");
      return;
    }
    const qty = parseInt(formData.quantity, 10);
    if (!qty || qty < 1) {
      alert("Please enter a valid quantity");
      return;
    }
    if (!formData.category_id) {
      alert("Please select a category");
      return;
    }

    setShowCopiesPopup(true);
  };

  const inputs = [
    {
      name: "file_info",
      type: "custom",
      render: () => (
        <span className=" block text-end text-[0.6875rem] -mb-2.5 font-medium text-[#000035]  dark:text-[#D7D7D7]">
          {fileName}
        </span>
      ),
    },
    {
      name: "name",
      type: "text",
      placeholder: "Name",
      required: true,
      rightIcon: <Image size={24} />,
      onRightIconClick: () => fileInputRef.current?.click(),
    },
    {
      name: "description",
      type: "textarea",
      placeholder: "Description (auto-generated by default)",
      required: false,
      rows: 1,
      className: "resize-y",
    },
    {
      name: "quantity",
      type: "number",
      placeholder: "Quantity",
      required: true,
    },
    {
      name: "category_id",
      type: "select",
      placeholder: "Category",
      options: (categories || []).map((cat) => ({
        value: cat.category_id,
        label: cat.category_name,
      })),
    },
  ];

  const customLayout = [
    ...(fileName ? [{ type: "flex", inputs: ["file_info"] }] : []),
    { columns: 1, inputs: ["name"] },
    { columns: 1, inputs: ["description"] },
    { columns: 2, inputs: ["quantity", "category_id"] },
  ];

  return (
    <>
      <FormLayout
        show={showPopup}
        onClose={() => {
          setShowPopup(false);
          setEditMode(false);
          setFileName("");
        }}
        title={editMode ? "Edit Book" : "Add Book"}
        onSubmit={handleSubmit}
        inputs={inputs}
        formData={formData}
        onFormChange={onFormChange}
        submitButtonText={editMode ? "Edit Copies" : "Enter IDs"}
        onCancel={() => {
          setShowPopup(false);
          setEditMode(false);
          setFileName("");
        }}
        icon={<BookOpen size={24} strokeWidth={2.3} />}
        customLayout={customLayout}
      >
        {/* Hidden file input for cover image upload */}
        <input
          type="file"
          ref={fileInputRef}
          className="hidden"
          accept="image/*"
          onChange={handleFileChange}
        />
      </FormLayout>
      <BookCopiesPopup
        show={showCopiesPopup}
        onClose={() => setShowCopiesPopup(false)}
        quantity={formData.quantity}
        bookCopies={formData.BookCopies}
        onSave={handleSaveBookCopies}
        bookId={formData.book_id}
        editMode={editMode}
      />
    </>
  );
}

export default BookFormPopup;
